from setuptools import setup

setup(
    name='sfmutils',
    version='2.3.0',
    url='https://github.com/gwu-libraries/sfm-utils',
    author='Social Feed Manager',
    author_email='sfm@gwu.edu',
    packages=['sfmutils'],
    description="Utilities to support Social Feed Manager.",
    platforms=['POSIX'],
    test_suite='tests',
    scripts=['sfmutils/stream_consumer.py', 'sfmutils/find_warcs.py'],
    install_requires=['pytz==2020.1',
                      'requests==2.23.0',
                      'kombu==4.6.8',
                      'librabbitmq==2.0.0',
                      'warcio==1.7.3',
                      'iso8601==0.1.12',
                      'petl==1.3.0',
                      'xlsxwriter==1.2.8',
                      'idna==2.7'],
    tests_require=['mock==4.0.2',
                   'vcrpy==4.0.2',
                   'python-dateutil==2.8.1'],
    classifiers=[
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Programming Language :: Python :: 3',
        'Development Status :: 4 - Beta',
    ],
)
